-- MySQL Script generated by MySQL Workbench
-- 05/12/19 21:02:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET latin1 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`libro` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(100) CHARACTER SET 'gbk' COLLATE 'gbk_bin' NULL DEFAULT NULL,
  `vsion` VARCHAR(30) CHARACTER SET 'gbk' COLLATE 'gbk_bin' NULL DEFAULT NULL,
  `autor` VARCHAR(100) CHARACTER SET 'gbk' COLLATE 'gbk_bin' NULL DEFAULT NULL,
  `cantidad` TINYINT(2) NULL DEFAULT NULL,
  `editorial` VARCHAR(50) CHARACTER SET 'gbk' COLLATE 'gbk_bin' NULL DEFAULT NULL,
  `foto` VARCHAR(100) CHARACTER SET 'gbk' COLLATE 'gbk_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COLLATE = gbk_bin;


-- -----------------------------------------------------
-- Table `proyecto`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`usuario` (
  `id_user` INT(11) NOT NULL,
  `usuario` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `nombre` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `proyecto`.`libro_prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`libro_prestamo` (
  `id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  `libro_id` INT(11) NOT NULL,
  `fecha_prestamo` DATE NULL DEFAULT NULL,
  `prestado_a` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  `fecha_devolucion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `libro_id`),
  INDEX `fk_libro_prestamo_usuario_idx` (`usuario_id` ASC),
  INDEX `fk_libro_prestamo_libro1_idx` (`libro_id` ASC),
  CONSTRAINT `fk_libro_prestamo_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `proyecto`.`usuario` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_prestamo_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `proyecto`.`libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `proyecto`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`permiso` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `slug` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `proyecto`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`rol` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `proyecto`.`permiso_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`permiso_rol` (
  `id` INT(11) NOT NULL,
  `rol_id` INT(11) NOT NULL,
  `permiso_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `rol_id`, `permiso_id`),
  INDEX `fk_permiso_rol_permiso1_idx` (`permiso_id` ASC),
  INDEX `fk_permiso_rol_rol1_idx` (`rol_id` ASC),
  CONSTRAINT `fk_permiso_rol_permiso1`
    FOREIGN KEY (`permiso_id`)
    REFERENCES `proyecto`.`permiso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permiso_rol_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `proyecto`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `proyecto`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`usuario_rol` (
  `id` INT(11) NOT NULL,
  `rol_id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `rol_id`, `usuario_id`),
  INDEX `fk_usuario_rol_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_usuario_rol_rol1_idx` (`rol_id` ASC),
  CONSTRAINT `fk_usuario_rol_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `proyecto`.`usuario` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `proyecto`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
